# Generated by Django 6.0.4 on 2026-04-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nome',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='endereco',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='parcelaacordo',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('VENCIDO', 'Vencido')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='responsavel',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='status',
            field=models.CharField(choices=[('OCUPADO', 'Ocupado'), ('VAGO', 'Vago')], default='OCUPADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('USUARIO', 'Usuário Padrão')], default='USUARIO', max_length=20),
        ),
    ]
