# Generated by Django 6.0.4 on 2026-05-14 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usuario_nome_alter_cobranca_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobranca',
            name='acordo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobrancas_geradas', to='api.acordo'),
        ),
        migrations.AddField(
            model_name='cobranca',
            name='numero_parcela_acordo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelaacordo',
            name='cobranca',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcela_acordo', to='api.cobranca'),
        ),
        migrations.AlterField(
            model_name='parcelaacordo',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20),
        ),
    ]
